"""Default configuration for the rebuilt basic framework."""

DEFAULTS = {
    "model": "resnet18",
    "data_root": "data/ECSSD",
    "split_file": "splits/trainval_seed_42.json",
    "image_size": 352,
    "batch_size": 16,
    "epochs": 100,
    "lr": 3e-4,
    "num_workers": 4,
    "seed": 42,
    "device": "cuda",
    "gpu_ids": "0,1",
    "output_dir": "runs/resnet18",
    "scheduler": "auto",
    "min_lr": 1e-6,
    "grad_clip": 1.0,
    "selection_metric": "max_f_measure",
    "augment_mode": "basic",
    "zoom_topk": 1,
    "zoom_patch_size": 128,
    "zoom_grid_size": 32,
    "zoom_coarse_weight": 0.4,
    "zoom_patch_weight": 0.5,
    "zoom_delta_weight": 0.001,
    "zoom_side_weight": 0.2,
    "zoom_loss": "hybrid",
}
